version: "3.8"

services:
  db:
    build:
      context: ./
      dockerfile: docker/postgres/Dockerfile
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - ${EXTERNAL_DB_PORT}:${DB_PORT}
  web:
    user: 1000:1000
    build:
      context: ./
      dockerfile: docker/web/Dockerfile
    volumes:
      - ./:/home/node/app
    command: npm run start-pm2
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.template:ro
    depends_on:
      - db
      - web
    ports:
      - ${EXTERNAL_NGINX_PORT_HTTP}:80
      - ${EXTERNAL_NGINX_PORT_HTTPS}:443
    environment:
      NGINX_EXTERNAL_HOST_HTTP: ${EXTERNAL_NGINX_PORT_HTTP}
      NGINX_EXTERNAL_HOST_HTTPS: ${EXTERNAL_NGINX_PORT_HTTPS}
      NODE_PORT: ${PORT}
    command: bash -c "envsubst '$${NGINX_EXTERNAL_HOST_HTTP},$${NGINX_EXTERNAL_HOST_HTTPS},$${NODE_PORT}' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"